// <auto-generated />
using System;
using Cabinet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cabinet.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260204104826_AddCertificateAndPaymentFields")]
    partial class AddCertificateAndPaymentFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cabinet.Models.CabinetInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Speciality")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CabinetInfo");
                });

            modelBuilder.Entity("Cabinet.Models.CategoryStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("category_stock");
                });

            modelBuilder.Entity("Cabinet.Models.Consultation", b =>
                {
                    b.Property<int>("IdConsultation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_consultation");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConsultation"));

                    b.Property<DateTime?>("ArretDebut")
                        .HasColumnType("datetime2")
                        .HasColumnName("arret_debut");

                    b.Property<DateTime?>("ArretFin")
                        .HasColumnType("datetime2")
                        .HasColumnName("arret_fin");

                    b.Property<int?>("ArretJours")
                        .HasColumnType("int")
                        .HasColumnName("arret_jours");

                    b.Property<string>("ArretMotif")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("arret_motif");

                    b.Property<bool?>("CertificatAptitude")
                        .HasColumnType("bit")
                        .HasColumnName("certificat_aptitude");

                    b.Property<string>("CertificatObservation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("certificat_observation");

                    b.Property<string>("Conduite")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("conduite");

                    b.Property<DateTime?>("DateConsultation")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_consultation");

                    b.Property<string>("Diagnostique")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("diagnostique");

                    b.Property<string>("Etat")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("etat");

                    b.Property<bool>("MutRemplie")
                        .HasColumnType("bit")
                        .HasColumnName("mut_remplie");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("payment_date");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("payment_method");

                    b.Property<decimal?>("PrixConsul")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("prix_consul");

                    b.Property<string>("ReceiptNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("receipt_number");

                    b.Property<decimal?>("Remise")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("remise");

                    b.Property<string>("Service")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("service");

                    b.Property<string>("Signe")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("signe");

                    b.Property<string>("TFev")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("t_fev");

                    b.Property<string>("TFvc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("t_fvc");

                    b.Property<string>("TGly")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("t_gly");

                    b.Property<string>("TImc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("t_imc");

                    b.Property<string>("TLdl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("t_ldl");

                    b.Property<string>("TPoid")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("t_poid");

                    b.Property<string>("TSpo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("t_spo");

                    b.Property<string>("TTaille")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("t_taille");

                    b.Property<string>("TTemp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("t_temp");

                    b.Property<string>("TTension")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("t_tension");

                    b.HasKey("IdConsultation");

                    b.HasIndex("PatientId");

                    b.ToTable("Consultation");
                });

            modelBuilder.Entity("Cabinet.Models.ConsultationService", b =>
                {
                    b.Property<int>("IdLink")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_link");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLink"));

                    b.Property<int?>("IdConsultation")
                        .HasColumnType("int")
                        .HasColumnName("id_consultation");

                    b.Property<int?>("IdService")
                        .HasColumnType("int")
                        .HasColumnName("id_service");

                    b.HasKey("IdLink");

                    b.ToTable("consultation_service");
                });

            modelBuilder.Entity("Cabinet.Models.Employer", b =>
                {
                    b.Property<int>("IdEmployer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmployer"));

                    b.Property<string>("Adresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("Fonction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotPasse")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("mot_passe");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEmployer");

                    b.ToTable("Employer");
                });

            modelBuilder.Entity("Cabinet.Models.Medicament", b =>
                {
                    b.Property<double?>("Id")
                        .HasColumnType("float")
                        .HasColumnName("ID");

                    b.Property<string>("Code")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CODE");

                    b.Property<string>("Dci1")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DCI1");

                    b.Property<string>("Dosage1")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DOSAGE1");

                    b.Property<string>("Forme")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("FORME");

                    b.Property<string>("Nom")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("NOM");

                    b.Property<double?>("Ph")
                        .HasColumnType("float")
                        .HasColumnName("PH");

                    b.Property<double?>("Ppv")
                        .HasColumnType("float")
                        .HasColumnName("PPV");

                    b.Property<string>("Presentation")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PRESENTATION");

                    b.Property<string>("PrincepsGenerique")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PRINCEPS_GENERIQUE");

                    b.Property<double?>("PrixBr")
                        .HasColumnType("float")
                        .HasColumnName("PRIX_BR");

                    b.Property<string>("TauxRemboursement")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TAUX_REMBOURSEMENT");

                    b.Property<string>("UniteDosage1")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("UNITE_DOSAGE1");

                    b.HasKey("Id");

                    b.ToTable("medicaments");
                });

            modelBuilder.Entity("Cabinet.Models.Ordonnance", b =>
                {
                    b.Property<int>("OrdonnanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrdonnanceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrdonnanceID"));

                    b.Property<DateTime>("DatePrescription")
                        .HasColumnType("datetime2")
                        .HasColumnName("DatePrescription");

                    b.Property<int>("PatientID")
                        .HasColumnType("int")
                        .HasColumnName("PatientID");

                    b.HasKey("OrdonnanceID");

                    b.HasIndex("PatientID");

                    b.ToTable("Ordonnances");
                });

            modelBuilder.Entity("Cabinet.Models.OrdonnanceMedicament", b =>
                {
                    b.Property<int>("OrdonnanceID")
                        .HasColumnType("int")
                        .HasColumnName("OrdonnanceID");

                    b.Property<string>("MedicamentID")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)")
                        .HasColumnName("MedicamentID");

                    b.Property<string>("Quantite")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("quantite");

                    b.HasKey("OrdonnanceID", "MedicamentID");

                    b.ToTable("OrdonnanceMedicaments");
                });

            modelBuilder.Entity("Cabinet.Models.Patient", b =>
                {
                    b.Property<int>("IdPatient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_patient");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPatient"));

                    b.Property<string>("Adresse")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("adresse");

                    b.Property<string>("Cin")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("cin");

                    b.Property<DateTime?>("DateNaiss")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_naiss");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nom")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nom");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Prenom")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("prenom");

                    b.Property<string>("Sexe")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("sexe");

                    b.HasKey("IdPatient");

                    b.ToTable("patient");
                });

            modelBuilder.Entity("Cabinet.Models.Rendezvous", b =>
                {
                    b.Property<int>("IdRdv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rdv");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRdv"));

                    b.Property<DateTime>("DateHeure")
                        .HasColumnType("datetime2")
                        .HasColumnName("dateheure");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("nom");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("phone");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("prenom");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("service");

                    b.Property<string>("Sexe")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("sexe");

                    b.HasKey("IdRdv");

                    b.ToTable("rendezvous");
                });

            modelBuilder.Entity("Cabinet.Models.Service", b =>
                {
                    b.Property<int>("IdService")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_service");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdService"));

                    b.Property<string>("NomService")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("service");

                    b.Property<string>("Obs")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("obs");

                    b.Property<decimal?>("Prix")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("prix");

                    b.HasKey("IdService");

                    b.ToTable("services");
                });

            modelBuilder.Entity("Cabinet.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_produit");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Alarme")
                        .HasColumnType("int")
                        .HasColumnName("alarme");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("nom_produit");

                    b.Property<string>("Observation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("obs");

                    b.Property<int>("Quantite")
                        .HasColumnType("int")
                        .HasColumnName("quantite");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("stock");
                });

            modelBuilder.Entity("Cabinet.Models.StockMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateMouvement")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployerId")
                        .HasColumnType("int");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployerId");

                    b.HasIndex("StockId");

                    b.ToTable("stock_movements");
                });

            modelBuilder.Entity("Cabinet.Models.Consultation", b =>
                {
                    b.HasOne("Cabinet.Models.Patient", "Patient")
                        .WithMany("Consultations")
                        .HasForeignKey("PatientId");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Cabinet.Models.Ordonnance", b =>
                {
                    b.HasOne("Cabinet.Models.Patient", "Patient")
                        .WithMany("Ordonnances")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Cabinet.Models.Stock", b =>
                {
                    b.HasOne("Cabinet.Models.CategoryStock", "Category")
                        .WithMany("Produits")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Cabinet.Models.StockMovement", b =>
                {
                    b.HasOne("Cabinet.Models.Employer", "Employer")
                        .WithMany()
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cabinet.Models.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employer");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("Cabinet.Models.CategoryStock", b =>
                {
                    b.Navigation("Produits");
                });

            modelBuilder.Entity("Cabinet.Models.Patient", b =>
                {
                    b.Navigation("Consultations");

                    b.Navigation("Ordonnances");
                });
#pragma warning restore 612, 618
        }
    }
}
